algoritmo "semnome"
var
numero1,numero2:inteiro
inicio
escreva("insira um numero: ")
leia(numero1)
escreva("insira um numero: ")
leia(numero2)
escreva("resultado da soma: ")
escreva(numero1+numero2)
escreva("/")

escreva("resultado da subtração: ")
escreva(numero1-numero2)
escreva("/")

escreva("resultado da multiplicação: ")
escreva(numero1*numero2)
escreva("/")

escreva("resultado da divisão")
escreva(numero1/numero2)
fimalgoritmo
